// ---------------------------------------------------------------------
// Static NFL player pool. A hand-picked snapshot for building rosters,
// not a live feed -- trades/injuries/depth-chart moves won't show up
// here automatically.
// ---------------------------------------------------------------------
export const PLAYERS = [
  {name:"Josh Allen", pos:"QB", team:"BUF"}, {name:"Patrick Mahomes", pos:"QB", team:"KC"},
  {name:"Lamar Jackson", pos:"QB", team:"BAL"}, {name:"Jayden Daniels", pos:"QB", team:"WAS"},
  {name:"Joe Burrow", pos:"QB", team:"CIN"}, {name:"Jalen Hurts", pos:"QB", team:"PHI"},
  {name:"Justin Herbert", pos:"QB", team:"LAC"}, {name:"C.J. Stroud", pos:"QB", team:"HOU"},
  {name:"Brock Purdy", pos:"QB", team:"SF"}, {name:"Kyler Murray", pos:"QB", team:"ARI"},
  {name:"Dak Prescott", pos:"QB", team:"DAL"}, {name:"Jordan Love", pos:"QB", team:"GB"},
  {name:"Matthew Stafford", pos:"QB", team:"LAR"}, {name:"Trevor Lawrence", pos:"QB", team:"JAX"},
  {name:"Bo Nix", pos:"QB", team:"DEN"}, {name:"Baker Mayfield", pos:"QB", team:"TB"},
  {name:"Caleb Williams", pos:"QB", team:"CHI"}, {name:"Jared Goff", pos:"QB", team:"DET"},
  {name:"Aaron Rodgers", pos:"QB", team:"PIT"}, {name:"Geno Smith", pos:"QB", team:"LV"},
  {name:"Tua Tagovailoa", pos:"QB", team:"MIA"}, {name:"Sam Darnold", pos:"QB", team:"SEA"},
  {name:"Kirk Cousins", pos:"QB", team:"ATL"}, {name:"Bryce Young", pos:"QB", team:"CAR"},
  {name:"Drake Maye", pos:"QB", team:"NE"}, {name:"Daniel Jones", pos:"QB", team:"IND"},
  {name:"Russell Wilson", pos:"QB", team:"NYG"}, {name:"J.J. McCarthy", pos:"QB", team:"MIN"},
  {name:"Justin Fields", pos:"QB", team:"NYJ"}, {name:"Michael Penix Jr.", pos:"QB", team:"ATL"},
  {name:"Will Levis", pos:"QB", team:"TEN"}, {name:"Derek Carr", pos:"QB", team:"NO"},

  {name:"Christian McCaffrey", pos:"RB", team:"SF"}, {name:"Bijan Robinson", pos:"RB", team:"ATL"},
  {name:"Saquon Barkley", pos:"RB", team:"PHI"}, {name:"Jahmyr Gibbs", pos:"RB", team:"DET"},
  {name:"Derrick Henry", pos:"RB", team:"BAL"}, {name:"De'Von Achane", pos:"RB", team:"MIA"},
  {name:"Kyren Williams", pos:"RB", team:"LAR"}, {name:"Jonathan Taylor", pos:"RB", team:"IND"},
  {name:"Josh Jacobs", pos:"RB", team:"GB"}, {name:"Breece Hall", pos:"RB", team:"NYJ"},
  {name:"Bucky Irving", pos:"RB", team:"TB"}, {name:"James Cook", pos:"RB", team:"BUF"},
  {name:"Kenneth Walker III", pos:"RB", team:"SEA"}, {name:"Chuba Hubbard", pos:"RB", team:"CAR"},
  {name:"Alvin Kamara", pos:"RB", team:"NO"}, {name:"Aaron Jones", pos:"RB", team:"MIN"},
  {name:"James Conner", pos:"RB", team:"ARI"}, {name:"Chase Brown", pos:"RB", team:"CIN"},
  {name:"Rhamondre Stevenson", pos:"RB", team:"NE"}, {name:"Joe Mixon", pos:"RB", team:"HOU"},
  {name:"Tony Pollard", pos:"RB", team:"TEN"}, {name:"D'Andre Swift", pos:"RB", team:"CHI"},
  {name:"Najee Harris", pos:"RB", team:"LAC"}, {name:"Javonte Williams", pos:"RB", team:"DAL"},
  {name:"Brian Robinson Jr.", pos:"RB", team:"WAS"}, {name:"Zach Charbonnet", pos:"RB", team:"SEA"},
  {name:"Rachaad White", pos:"RB", team:"TB"}, {name:"Isiah Pacheco", pos:"RB", team:"KC"},
  {name:"Austin Ekeler", pos:"RB", team:"WAS"}, {name:"Tyjae Spears", pos:"RB", team:"TEN"},
  {name:"Jaylen Warren", pos:"RB", team:"PIT"}, {name:"Ray Davis", pos:"RB", team:"BUF"},

  {name:"Ja'Marr Chase", pos:"WR", team:"CIN"}, {name:"Justin Jefferson", pos:"WR", team:"MIN"},
  {name:"CeeDee Lamb", pos:"WR", team:"DAL"}, {name:"Amon-Ra St. Brown", pos:"WR", team:"DET"},
  {name:"Puka Nacua", pos:"WR", team:"LAR"}, {name:"Malik Nabers", pos:"WR", team:"NYG"},
  {name:"Nico Collins", pos:"WR", team:"HOU"}, {name:"A.J. Brown", pos:"WR", team:"PHI"},
  {name:"Drake London", pos:"WR", team:"ATL"}, {name:"Brian Thomas Jr.", pos:"WR", team:"JAX"},
  {name:"Ladd McConkey", pos:"WR", team:"LAC"}, {name:"Tee Higgins", pos:"WR", team:"CIN"},
  {name:"Mike Evans", pos:"WR", team:"TB"}, {name:"DK Metcalf", pos:"WR", team:"PIT"},
  {name:"Terry McLaurin", pos:"WR", team:"WAS"}, {name:"DJ Moore", pos:"WR", team:"CHI"},
  {name:"Garrett Wilson", pos:"WR", team:"NYJ"}, {name:"Davante Adams", pos:"WR", team:"LAR"},
  {name:"Rashee Rice", pos:"WR", team:"KC"}, {name:"Xavier Worthy", pos:"WR", team:"KC"},
  {name:"Zay Flowers", pos:"WR", team:"BAL"}, {name:"Jaxon Smith-Njigba", pos:"WR", team:"SEA"},
  {name:"Chris Olave", pos:"WR", team:"NO"}, {name:"Jameson Williams", pos:"WR", team:"DET"},
  {name:"Courtland Sutton", pos:"WR", team:"DEN"}, {name:"Jerry Jeudy", pos:"WR", team:"CLE"},
  {name:"Jordan Addison", pos:"WR", team:"MIN"}, {name:"Rome Odunze", pos:"WR", team:"CHI"},
  {name:"Calvin Ridley", pos:"WR", team:"TEN"}, {name:"Keenan Allen", pos:"WR", team:"LAC"},
  {name:"Marvin Harrison Jr.", pos:"WR", team:"ARI"}, {name:"Tank Dell", pos:"WR", team:"HOU"},
  {name:"Deebo Samuel", pos:"WR", team:"WAS"}, {name:"Christian Kirk", pos:"WR", team:"HOU"},
  {name:"Diontae Johnson", pos:"WR", team:"BAL"}, {name:"George Pickens", pos:"WR", team:"DAL"},
  {name:"Amari Cooper", pos:"WR", team:"LV"}, {name:"Michael Pittman Jr.", pos:"WR", team:"IND"},

  {name:"Travis Kelce", pos:"TE", team:"KC"}, {name:"Sam LaPorta", pos:"TE", team:"DET"},
  {name:"Trey McBride", pos:"TE", team:"ARI"}, {name:"Mark Andrews", pos:"TE", team:"BAL"},
  {name:"George Kittle", pos:"TE", team:"SF"}, {name:"Brock Bowers", pos:"TE", team:"LV"},
  {name:"Evan Engram", pos:"TE", team:"DEN"}, {name:"Kyle Pitts", pos:"TE", team:"ATL"},
  {name:"David Njoku", pos:"TE", team:"CLE"}, {name:"Dallas Goedert", pos:"TE", team:"PHI"},
  {name:"Jake Ferguson", pos:"TE", team:"DAL"}, {name:"Cole Kmet", pos:"TE", team:"CHI"},
  {name:"Pat Freiermuth", pos:"TE", team:"PIT"}, {name:"Dalton Kincaid", pos:"TE", team:"BUF"},
  {name:"T.J. Hockenson", pos:"TE", team:"MIN"}, {name:"Tucker Kraft", pos:"TE", team:"GB"},

  {name:"Anthony Richardson", pos:"QB", team:"IND"}, {name:"Tyler Shough", pos:"QB", team:"NO"},

  {name:"Tyrone Tracy Jr.", pos:"RB", team:"NYG"}, {name:"Ty Chandler", pos:"RB", team:"MIN"},
  {name:"Blake Corum", pos:"RB", team:"LAR"}, {name:"MarShawn Lloyd", pos:"RB", team:"GB"},
  {name:"Jaylen Wright", pos:"RB", team:"MIA"}, {name:"Braelon Allen", pos:"RB", team:"NYJ"},
  {name:"Devin Singletary", pos:"RB", team:"NYG"}, {name:"Antonio Gibson", pos:"RB", team:"NE"},
  {name:"Zamir White", pos:"RB", team:"LV"}, {name:"Roschon Johnson", pos:"RB", team:"CHI"},
  {name:"Justice Hill", pos:"RB", team:"BAL"}, {name:"Jerome Ford", pos:"RB", team:"CLE"},
  {name:"Ezekiel Elliott", pos:"RB", team:"DAL"}, {name:"Samaje Perine", pos:"RB", team:"KC"},
  {name:"Sean Tucker", pos:"RB", team:"TB"},

  {name:"Wan'Dale Robinson", pos:"WR", team:"NYG"}, {name:"Khalil Shakir", pos:"WR", team:"BUF"},
  {name:"Josh Downs", pos:"WR", team:"IND"}, {name:"Adonai Mitchell", pos:"WR", team:"IND"},
  {name:"Ricky Pearsall", pos:"WR", team:"SF"}, {name:"Xavier Legette", pos:"WR", team:"CAR"},
  {name:"Keon Coleman", pos:"WR", team:"BUF"}, {name:"Jayden Reed", pos:"WR", team:"GB"},
  {name:"Romeo Doubs", pos:"WR", team:"GB"}, {name:"Darnell Mooney", pos:"WR", team:"ATL"},
  {name:"Curtis Samuel", pos:"WR", team:"BUF"}, {name:"Hollywood Brown", pos:"WR", team:"KC"},
  {name:"Tyler Lockett", pos:"WR", team:"TEN"}, {name:"Elijah Moore", pos:"WR", team:"CLE"},
  {name:"Rashid Shaheed", pos:"WR", team:"NO"}, {name:"Jauan Jennings", pos:"WR", team:"SF"},
  {name:"Josh Palmer", pos:"WR", team:"LAC"}, {name:"Quentin Johnston", pos:"WR", team:"LAC"},

  {name:"Hunter Henry", pos:"TE", team:"NE"}, {name:"Colby Parkinson", pos:"TE", team:"LAR"},
  {name:"Chig Okonkwo", pos:"TE", team:"TEN"}, {name:"Isaiah Likely", pos:"TE", team:"BAL"},
  {name:"Noah Fant", pos:"TE", team:"CIN"}, {name:"Juwan Johnson", pos:"TE", team:"NO"},
  {name:"Cade Otton", pos:"TE", team:"TB"}, {name:"Zach Ertz", pos:"TE", team:"WAS"},

  {name:"Justin Tucker", pos:"K", team:"BAL"}, {name:"Harrison Butker", pos:"K", team:"KC"},
  {name:"Brandon Aubrey", pos:"K", team:"DAL"}, {name:"Jake Bates", pos:"K", team:"DET"},
  {name:"Tyler Bass", pos:"K", team:"BUF"}, {name:"Chris Boswell", pos:"K", team:"PIT"},
  {name:"Cameron Dicker", pos:"K", team:"LAC"}, {name:"Jake Elliott", pos:"K", team:"PHI"},
  {name:"Younghoe Koo", pos:"K", team:"ATL"}, {name:"Ka'imi Fairbairn", pos:"K", team:"HOU"},
  {name:"Wil Lutz", pos:"K", team:"DEN"}, {name:"Evan McPherson", pos:"K", team:"CIN"},
  {name:"Chad Ryland", pos:"K", team:"ARI"}, {name:"Ryan Fitzgerald", pos:"K", team:"CAR"},
  {name:"Cairo Santos", pos:"K", team:"CHI"}, {name:"Dustin Hopkins", pos:"K", team:"CLE"},
  {name:"Brandon McManus", pos:"K", team:"GB"}, {name:"Spencer Shrader", pos:"K", team:"IND"},
  {name:"Cam Little", pos:"K", team:"JAX"}, {name:"Joshua Karty", pos:"K", team:"LAR"},
  {name:"Daniel Carlson", pos:"K", team:"LV"}, {name:"Jason Sanders", pos:"K", team:"MIA"},
  {name:"Will Reichard", pos:"K", team:"MIN"}, {name:"Andy Borregales", pos:"K", team:"NE"},
  {name:"Blake Grupe", pos:"K", team:"NO"}, {name:"Graham Gano", pos:"K", team:"NYG"},
  {name:"Nick Folk", pos:"K", team:"NYJ"}, {name:"Jason Myers", pos:"K", team:"SEA"},
  {name:"Jake Moody", pos:"K", team:"SF"}, {name:"Chase McLaughlin", pos:"K", team:"TB"},
  {name:"Joey Slye", pos:"K", team:"TEN"}, {name:"Zane Gonzalez", pos:"K", team:"WAS"},

  {name:"49ers D/ST", pos:"DEF", team:"SF"}, {name:"Ravens D/ST", pos:"DEF", team:"BAL"},
  {name:"Steelers D/ST", pos:"DEF", team:"PIT"}, {name:"Cowboys D/ST", pos:"DEF", team:"DAL"},
  {name:"Eagles D/ST", pos:"DEF", team:"PHI"}, {name:"Broncos D/ST", pos:"DEF", team:"DEN"},
  {name:"Chiefs D/ST", pos:"DEF", team:"KC"}, {name:"Vikings D/ST", pos:"DEF", team:"MIN"},
  {name:"Bills D/ST", pos:"DEF", team:"BUF"}, {name:"Texans D/ST", pos:"DEF", team:"HOU"},
  {name:"Packers D/ST", pos:"DEF", team:"GB"}, {name:"Lions D/ST", pos:"DEF", team:"DET"},
  {name:"Cardinals D/ST", pos:"DEF", team:"ARI"}, {name:"Falcons D/ST", pos:"DEF", team:"ATL"},
  {name:"Panthers D/ST", pos:"DEF", team:"CAR"}, {name:"Bears D/ST", pos:"DEF", team:"CHI"},
  {name:"Bengals D/ST", pos:"DEF", team:"CIN"}, {name:"Browns D/ST", pos:"DEF", team:"CLE"},
  {name:"Colts D/ST", pos:"DEF", team:"IND"}, {name:"Jaguars D/ST", pos:"DEF", team:"JAX"},
  {name:"Chargers D/ST", pos:"DEF", team:"LAC"}, {name:"Rams D/ST", pos:"DEF", team:"LAR"},
  {name:"Raiders D/ST", pos:"DEF", team:"LV"}, {name:"Dolphins D/ST", pos:"DEF", team:"MIA"},
  {name:"Patriots D/ST", pos:"DEF", team:"NE"}, {name:"Saints D/ST", pos:"DEF", team:"NO"},
  {name:"Giants D/ST", pos:"DEF", team:"NYG"}, {name:"Jets D/ST", pos:"DEF", team:"NYJ"},
  {name:"Seahawks D/ST", pos:"DEF", team:"SEA"}, {name:"Buccaneers D/ST", pos:"DEF", team:"TB"},
  {name:"Titans D/ST", pos:"DEF", team:"TEN"}, {name:"Commanders D/ST", pos:"DEF", team:"WAS"},
];

// Each entry gets a stable id so it can be tracked in localStorage.
PLAYERS.forEach((p, i) => p.id = i);

export function playerById(id) {
  return PLAYERS.find(p => p.id === id);
}

export const SLOTS = [
  {key:"QB",    label:"QB",    eligible:["QB"]},
  {key:"RB1",   label:"RB",    eligible:["RB"]},
  {key:"RB2",   label:"RB",    eligible:["RB"]},
  {key:"WR1",   label:"WR",    eligible:["WR"]},
  {key:"WR2",   label:"WR",    eligible:["WR"]},
  {key:"WR3",   label:"WR",    eligible:["WR"]},
  {key:"TE",    label:"TE",    eligible:["TE"]},
  {key:"FLEX",  label:"FLEX",  eligible:["RB","WR","TE"]},
  {key:"K",     label:"K",     eligible:["K"]},
  {key:"DEF",   label:"DEF",   eligible:["DEF"]},
  {key:"BN1",   label:"BENCH", eligible:["QB","RB","WR","TE","K","DEF"]},
  {key:"BN2",   label:"BENCH", eligible:["QB","RB","WR","TE","K","DEF"]},
  {key:"BN3",   label:"BENCH", eligible:["QB","RB","WR","TE","K","DEF"]},
  {key:"BN4",   label:"BENCH", eligible:["QB","RB","WR","TE","K","DEF"]},
  {key:"BN5",   label:"BENCH", eligible:["QB","RB","WR","TE","K","DEF"]},
];
export const STARTER_SLOTS = SLOTS.filter(s => s.label !== "BENCH");
export const BENCH_SLOTS = SLOTS.filter(s => s.label === "BENCH");

export const POS_COLOR = {
  QB: "var(--qb)", RB: "var(--rb)", WR: "var(--wr)", TE: "var(--te)",
  FLEX: "var(--flex)", K: "var(--k)", DEF: "var(--def)", BENCH: "var(--bench)",
};
